version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automation"
      - "actions"
    cooldown:
      default-days: 7
      semver-major: 14
      semver-minor: 7
      semver-patch: 3
      dev: 0
