name: Rebuild dependants against the new revisions

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'flake.lock'
      - 'emacs.nix'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - name: Build Emacs executable
      run: |
        if [[ -s $($command --dry-run) ]]; then
          $command --print-build-logs
        else
          echo Nothing to be built.
        fi
      env:
        command: 'nix build .#emacs-pgtk'

    - name: Check the homelab flake
    # The inputs of emacs-config aren't correctly updated here.
      run: |
        nix flake check github:akirak/homelab \
            --accept-flake-config --no-write-lock-file \
            --update-input emacs-config \
            --override-input emacs-config/flake-pins . \
            --inputs-from .
