name: Build Emacs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'flake.lock'
      - 'emacs.nix'

jobs:
  build-emacs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - name: Build Emacs executable
      run: |
        if [[ -s $($command --dry-run) ]]; then
          $command --print-build-logs
        else
          echo Nothing to be built.
        fi
      env:
        command: 'nix build .#emacs-pgtk'

  dispatch:
    needs: ['build-emacs']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: akirak/emacs-config
          event-type: rebuild
          token: ${{ secrets.PAT }}
          client-payload: '{"flake_inputs_from":"github:akirak/flake-pins/${{ github.sha }}"}'
