name: Rebuild dependants against the new revisions

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'flake.lock'
      - 'emacs.nix'

jobs:
  emacs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output:
        - emacs
        - emacs-pgtk
    steps:
    - uses: actions/checkout@v4
      with:
        path: flake-pins

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - name: Build Emacs executable
      working-directory: ./flake-pins
      run: |
        if [[ $(nix path-info $(nix eval .#${{ matrix.output }}.outPath --raw) --json \
                    --store https://nix-community.cachix.org 2>/dev/null \
                    | jq '.[0].valid') = false ]]
        then
          nix build .#${{ matrix.output }} --print-build-logs
        else
          echo Nothing to be built.
        fi

  homelab:
    runs-on: ubuntu-latest
    needs: emacs
    steps:
    - uses: actions/checkout@v4
      with:
        path: flake-pins

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - name: Check out homelab
      uses: actions/checkout@v4
      with:
        repository: akirak/homelab
        path: homelab

    # The inputs of emacs-config aren't correctly updated here.
    - name: Check the homelab flake (before updating)
      run: |
        nix flake check --print-build-logs --show-trace
      working-directory: ./homelab

    # The inputs of emacs-config aren't correctly updated here.
    - name: Update the homelab flake
      run: |
        nix flake update \
            --override-input emacs-config/flake-pins ../flake-pins \
            --inputs-from ../flake-pins
      working-directory: ./homelab

    # The inputs of emacs-config aren't correctly updated here.
    - name: Check the homelab flake (after updating)
      run: |
        nix flake check --print-build-logs --show-trace
      working-directory: ./homelab
