name: Dispatch downstream updates

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
    - registry.json

jobs:
  dispatch:
    strategy:
      matrix:
        include:
        # The flake update in emacs-config should trigger subsequent updates in
        # akirak/homelab as well. See
        # <https://github.com/akirak/emacs-config/commit/1a8c71755a9b055d2839b4dc5d8b57f4838cda44>.
        - repo: akirak/emacs-config
          event: flake-update
        - repo: akirak/flake-templates
          event: check

    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.repo }}
          event-type: ${{ matrix.event }}
