name: Trigger updates

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - registry.json

jobs:
  dispatch:
    strategy:
      matrix:
        repo:
        - akirak/emacs-config
        - akirak/homelab
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.repo }}
          event-type: flake-update
