name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2,12,22 * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: |
          root="$PWD"
          for dir in . deps/flakes deps/non-flakes
          do
            cd "$dir"
            nix flake update --inputs-from "path:$root"
            cd -
          done

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v7
        with:
          token: ${{ secrets.PAT_FOR_PR }}
          title: 'chore: Update root flake.lock'
