name: Update the registry from the flake.lock
on:
  pull_request:
    paths: 'flake.lock'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Regenerate the registry
        run: |
          nix build .#registry
          jq . result > registry.json
          git diff registry.json
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v6
        with:
          commit_message: 'chore: Update the flake registry'
          file_pattern: registry.json
