name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2,12,22 * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
        with:
          persist-credentials: false

      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

      - name: Update flake inputs
        run: |
          nix flake update

          root="$PWD"
          for dir in deps/flakes deps/non-flakes
          do
            cd "$dir"
            nix flake update --inputs-from "path:$root"
            cd -
          done

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v7
        with:
          token: ${{ secrets.PAT_FOR_PR }}
          title: 'chore: Update root flake.lock'
